const products = [
  {
    name: "هدفون بلوتوثی بی‌سیم ایرپاد",
    image: "/images/airpods.jpg",
    description:
      "تکنولوژی بلوتوث به شما اجازه می‌دهد به دستگاه‌های سازگار بدون سیم متصل شوید. صدای با کیفیت AAC تجربه شنیداری فراگیر ارائه می‌دهد. میکروفون داخلی امکان پاسخگویی به تماس‌ها هنگام کار را فراهم می‌کند.",
    brand: "اپل",
    category: "الکترونیکی",
    price: 200000,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
    user: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "آیفون ۱۱ پرو با حافظه ۲۵۶ گیگابایت",
    image: "/images/phone.jpg",
    description:
      "معرفی آیفون ۱۱ پرو. سیستم دوربین سه‌گانه متحول‌کننده که قابلیت‌های زیادی را بدون پیچیدگی اضافه می‌کند. جهشی بی‌سابقه در عمر باتری.",
    brand: "اپل",
    category: "الکترونیکی",
    price: 120000,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
    user: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "دوربین DSLR کنون EOS 80D",
    image: "/images/camera.jpg",
    description:
      "با مشخصات تصویربرداری همه‌جانبه، دوربین Canon EOS 80D خود را با دو سیستم فوکوس قوی و طراحی بصری معرفی می‌کند.",
    brand: "کنون",
    category: "الکترونیکی",
    price: 1300000,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
    user: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "پلی‌استیشن ۵ پرو سفید سونی",
    image: "/images/playstation.jpg",
    description:
      "مرکز نهایی سرگرمی خانگی با پلی‌استیشن شروع می‌شود. چه به بازی علاقه‌مند باشید، چه فیلم‌های HD، تلویزیون یا موسیقی.",
    brand: "سونی",
    category: "الکترونیکی",
    price: 500000,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
    user: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "موس گیمینگ Logitech سری G",
    image: "/images/mouse.jpg",
    description:
      "با این موس گیمینگ Logitech LIGHTSYNC کنترل بهتری روی بازی‌های خود داشته باشید. شش دکمه قابل برنامه‌ریزی امکان شخصی‌سازی برای تجربه‌ای روان را فراهم می‌کند.",
    brand: "لاجیتک",
    category: "الکترونیکی",
    price: 800000,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
    user: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Amazon Echo Dot نسل سوم",
    image: "/images/alexa.jpg",
    description:
      "با Echo Dot آشنا شوید – محبوب‌ترین اسپیکر هوشمند ما با طراحی پارچه‌ای. جمع‌وجورترین اسپیکر هوشمند ما که به‌خوبی در فضای کوچک جا می‌گیرد.",
    brand: "آمازون",
    category: "الکترونیکی",
    price: 150000,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
    user: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export default products;
